handle stdout and stderr limits properly
engineer-man/piston pull request #643
Opened 2024-01-25 20:04 UTC by AbsoluteZero000

the checking of the length of the stdout and stderr was checking on the stdout and stderr before the addition of the data characters so it passes any length of characters as long as passing the limit is in the same buffer.

basically 
```
{
  "language": "python3",
  "version": "*",
  "files": [
    {
      "name": "test",
      "content": "print('h'*5000)"
    }
    
  ],
  "stdin": "2"
}
```
this passes when it shouldn't

2024-01-25 20:11 UTC, Brikaa approved these changes

2024-01-26 03:23 UTC, HexF requested changes

2024-01-26 03:23 UTC, HexF commented on docker-compose.dev.yaml
> -            - PISTON_REPO_URL=http://repo:8000/index
these lines should be here

2024-01-26 06:41 UTC, HexF approved these changes

2024-01-26 06:41 UTC, merged